"""First

Revision ID: 03f982d531eb
Revises: 
Create Date: 2025-01-19 11:31:50.930446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f982d531eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Электронная почта пользователя.'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Хэшированный пароль пользователя.'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя пользователя.'),
    sa.Column('last_name', sa.String(length=255), nullable=True, comment='Фамилия пользователя'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный идентификатор пользователя.'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи пользователя.'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления записи пользователя.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
